### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by hustmx721** [TQTQliu/ET-MVSNet#1]
Excellent works!After reading your paper,there still some problems confused me,would u mind publish the whole code of ET-MVSNet?Thanks a lot!Wish u best

**Comment by TQTQliu** [comment]
Hi, Thanks for your interest. I've been busy with other projects lately, I'll organize and open source it when I have some free time afterwards!

**Comment by TQTQliu** [comment]
Hi, Thanks for your interest. I've been busy with other projects lately, I'll organize and release the code when I have some free time afterwards!

**Comment by hustmx721** [comment]
what a genrous man as u! thanks again for your excellent work!Hope to see more outstanding works form u!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TQTQliu/ET-MVSNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月9日(星期一) 晚上8:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TQTQliu/ET-MVSNet] About the code (Issue #1)





 
Hi, Thanks for your interest. I've been busy with other projects lately, I'll organize and release the code when I have some free time afterwards!
