### ISSUE TITLE
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 64, 3, 3], but got 3-dimensional input of size [64, 104, 144] instead

### ISSUE THREAD

**Issue by Ttingyyy** [TQTQliu/ET-MVSNet#11]
![a53d05be325836a57ff39e855ab3585](https://github.com/TQTQliu/ET-MVSNet/assets/130437764/1673b4a7-99b6-4750-8b97-195cdde5123d)
您好，我不知道为什么下载的数据集在测试时会出现这个错误。

**Comment by TQTQliu** [comment]
根据报错的信息来看，输入Conv2d的数据维度是[64, 104, 144]，这是不正确的，应该是[B, 64, 104, 144] (其中B是batch size)，您可以先定位到具体的报错位置然后进行debug，或者反馈在issues上。

**Comment by Ttingyyy** [comment]
> 根据报错的信息来看，输入Conv2d的数据维度是[64, 104, 144]，这是不正确的，应该是[B, 64, 104, 144] (其中B是batch size)，您可以先定位到具体的报错位置然后进行debug，或者反馈在issues上。

感谢您的回复！我调试了test_dtu_dypcd.py文件，结果似乎显示在load下的预训练模型有问题。加载的数据集是没有问题的。希望能得到您的回复。
![image](https://github.com/TQTQliu/ET-MVSNet/assets/130437764/95079ba2-daee-4d5e-ae69-802db10992bb)
![image](https://github.com/TQTQliu/ET-MVSNet/assets/130437764/50842fcb-d6cd-43ad-bbac-d557f4a11ace)

**Comment by TQTQliu** [comment]
在linux上直接运行bash scripts/test_dtu.sh exp_name(见readme)是没问题的。如果想在windows上运行test_dtu_dypcd.py文件的话，您需要修改parser里的超参数值设置与脚本test_dtu.sh里的一致。根据您提供的报错信息，现在的模型和提供的预训练模型是不一致的，应该是parser里超参数设置没有对应上的问题。

**Comment by Ttingyyy** [comment]
> 在linux上直接运行bash scripts/test_dtu.sh exp_name(见readme)是没问题的。如果想在windows上运行test_dtu_dypcd.py文件的话，您需要修改parser里的超参数值设置与脚本test_dtu.sh里的一致。根据您提供的报错信息，现在的模型和提供的预训练模型是不一致的，应该是parser里超参数设置没有对应上的问题。

我认可您的想法。但在服务器上运行仍然出现此错误：
![image](https://github.com/TQTQliu/ET-MVSNet/assets/130437764/2c101f97-388c-4e28-bb4a-6cb282659ffe)
![image](https://github.com/TQTQliu/ET-MVSNet/assets/130437764/c4f7590f-d3da-45a3-8a9a-e51bdf98f645)

**Comment by Ttingyyy** [comment]
> 在linux上直接运行bash scripts/test_dtu.sh exp_name(见readme)是没问题的。如果想在windows上运行test_dtu_dypcd.py文件的话，您需要修改parser里的超参数值设置与脚本test_dtu.sh里的一致。根据您提供的报错信息，现在的模型和提供的预训练模型是不一致的，应该是parser里超参数设置没有对应上的问题。

您好，我根据错误提示修改了一下代码，可以跑出来了。谢谢您一直以来的回复！！！
