### ISSUE TITLE
 different depth samples when testing on TnT dataset

### ISSUE THREAD

**Issue by xingchen2022** [TQTQliu/ET-MVSNet#13]
Thank you for your open-sourcing works!
I noticed that the script uses different depth samples when testing on intermediate (8,8,4,4) and advanced (16,8,4,4) sets of the TnT dataset. Is there any theory or assumption behind using different sets?

**Comment by TQTQliu** [comment]
Thanks for your attention, this is just based on experiments, we were inspired by previous work like [unimvsnet](https://arxiv.org/pdf/2201.01501) to change the number of depth hypotheses in the coarsest stage for TnT testing.
