### ISSUE TITLE
Question about the visualization of epipolar pairs.

### ISSUE THREAD

**Issue by Zhu980805** [TQTQliu/ET-MVSNet#5]
Great job! I am interested in how to visualize the epipolar pairs in the diagrams (Fig 1. (a), Fig. 3, and the center of Fig. 4) of your paper. Would you mind sharing the visualization code? I would appreciate it very much.

**Comment by TQTQliu** [comment]
Hello, thanks for your interest in our work. The procedure for visualizing epipolar pairs involves first utilizing the epipolar pair search algorithm to extract the pixel coordinates located on the epipolar lines of two images, and then visualizing these coordinates. You may also adjust the hyperparameters within the algorithm to achieve different visualization results, such as the search threshold δ (Table Algorithm 1 in the paper). I will arrange and organize the visualization code when time permits.
